name: ci

on: 
    push:
        branches:
            - "develop"

jobs:
  docker:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: neckcode
              password: dckr_pat_ozFUZZV0q-8JuvTeMMv2XxKhOys
          - name: Build and push
            run: |
                docker build --tag=neckcpde:latest ./
                docker push neckcpde:latest
