name: ci

on: 
    push:
        branches:
            - "develop"

jobs:
  docker:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v3

          - name: setup jdk 17
            uses: actions/setup-java@v3
            with:
              distribution: 'corretto'
              java-version: 17

          - name: build the app
            run: |
              mvn clean
              mvn -B package --file pom.xml
          - name: vars
            run: |
              pwd
              ls -a
              dir
              echo "user" ${{ vars.DOCKERHUB_USERNAME }}
              echo "secret" ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              secret:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: neckcode/todo:latest