name: todo-app

on: 
    push:
        branches:
            - "develop"

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${DOCKERHUB_USERNAME}
              password: ${DOCKERHUB_TOKEN}
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: $/todo:latest
