name: ci

on: 
    push:
        branches:
            - "develop"

jobs:
  docker:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: action/checkout@v4
          - name: vars
            run: |
              pwd
              ls -a
              dir
              echo "user" ${{ vars.DOCKERHUB_USERNAME }}
              echo "secret" ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              secret:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            run: |
                echo 
                docker build . -t neckcode/todo:latest 
                docker push neckcode/todo:latest
