name: ci

on: 
    push:
        branches:
            - "develop"

jobs:
  docker:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: neckcode
              password: dckr_pat_ozFUZZV0q-8JuvTeMMv2XxKhOys
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: $/todo:latest
