name: ci

on: 
    push:
        branches:
            - "develop"

jobs:
  docker:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            run: |
                docker build . -t neckcode/todo:latest 
                docker push neckcode/todo:latest
